version: '3.3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ellmo-network

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    links:
      - db:db
    networks:
      - ellmo-network
    volumes:
      - .:/app/server

  sync-server:
    build:
      context: ./
      dockerfile: ./sync/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - ellmo-network
    volumes:
      - .:/app

volumes:
  db-data:

networks:
  ellmo-network:
