name: Sync proto files

on:
  push:
    branches: [ 'main' ]
    paths:
      - proto/src/definitions/**/*.proto
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "Sync proto files"
    strategy:
      matrix:
        repo: [ 'ts-sdk' ]
    steps:
      - uses: passeidireto/trigger-external-workflow-action@main
        env:
          PAYLOAD_COMMIT_SHA: ${{ github.sha }}
        with:
          repository: polay-ai/${{ matrix.repo }}
          event: proto_update
          github_pat: ${{ secrets.SYNC_TOKEN }}
      
